language: cpp
compiler:
    - clang
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -qq update
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
    - echo "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get -qq update
    - sudo apt-get install clang-4.0 libclang-common-4.0-dev libclang-4.0-dev libclang1-4.0 libllvm4.0 libllvm4.0-dbg llvm-4.0 llvm-4.0-dev llvm-4.0-runtime
    - mkdir -p symlinks
    - ln -s /usr/bin/g++-4.9 symlinks/g++
    - ln -s /usr/bin/gcc-4.9 symlinks/gcc
    - ln -s /usr/bin/gcov-4.9 symlinks/gcov
    - ln -s /usr/bin/clang-4.0 symlinks/clang
    - ln -s /usr/bin/clang++-4.0 symlinks/clang++
    - ln -s /usr/bin/llvm-cov-4.0 symlinks/llvm-cov
    - ln -s /usr/bin/llvm-config-4.0 symlinks/llvm-config
    - ln -s /usr/bin/opt-4.0 symlinks/opt
    - export PATH=$PWD/symlinks:$PATH
script:
    - mkdir build
    - cd build
    - llvm-config --version
    - clang --version
    - cmake ..
    - make
    - ctest --output-on-failure
