language: cpp
compiler:
    - clang
before_install:
    - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ quantal main universe"
    - sudo apt-get update -qq
    - sudo apt-get install -qq llvm-dev
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
